# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b2ca390f61d777ae3c4f87ecc30648a6"
name = "Mileyo Subscription Os"
application_url = "https://mileyo-os.vercel.app/"
embedded = true

[app_proxy]
url = "https://mileyo-os.vercel.app/apps/box-builder"
subpath = "box-builder"
prefix = "apps"

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,read_orders,write_products,read_own_subscription_contracts,write_own_subscription_contracts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://mileyo-os.vercel.app/auth/callback",
  "https://mileyo-os.vercel.app/auth/shopify/callback"
]
