# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b7570c05a698930d95dc6e2121c044df"
name = "mileyo-subscription-os"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_metaobject_definitions,write_metaobjects,write_products,read_own_subscription_contracts,write_own_subscription_contracts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true


[app_proxy]
url = "https://151bbcb0a205.ngrok.app/apps/box-builder"
prefix = "apps"
subpath = "box-builder"